apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo
  labels:
    app: demo
  annotations:
    pod-info.details.html.spinnaker.io="Public endpoint -> a8d3bbb39119c424588df7e3deac67a5-666906212.us-east-2.elb.amazonaws.com"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: demo
  template:
    metadata:
      labels:
        app: demo
    spec:
      containers:
      - name: demo
        image: helvellyn/demo 
        imagePullPolicy: Always 
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: demo
spec:
  selector:
    app: demo
  ports:
    - port: 80
      targetPort: 8080
  type: LoadBalancer
